# Generated by Django 2.1.4 on 2018-12-21 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('cdate', models.DateField(default=datetime.datetime(2018, 12, 21, 17, 1, 7, 894288, tzinfo=utc))),
                ('due', models.DateField()),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='list.Category')),
            ],
        ),
    ]
