# Generated by Django 2.1.4 on 2018-12-21 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2018, 12, 21, 17, 11, 28, 651154, tzinfo=utc)),
        ),
    ]
