# Generated by Django 2.1.4 on 2018-12-22 06:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20181221_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='cdate',
            field=models.DateField(default=datetime.datetime(2018, 12, 22, 6, 41, 53, 895203, tzinfo=utc)),
        ),
    ]
